---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akka-persistence-sa
  namespace: akka-persistence

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akka-persistence-role
  namespace: akka-persistence
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: akka-persistence-rolebinding
  namespace: akka-persistence
subjects:
  - kind: ServiceAccount
    name: akka-persistence-sa
    namespace: akka-persistence
roleRef:
  kind: Role
  name: akka-persistence-role
  apiGroup: rbac.authorization.k8s.io
