apiVersion: v1
kind: Service
metadata:
  name: akka-persistence-service
  namespace: akka-persistence
  labels:
    app: akka-persistence
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: akka-persistence
  ports:
    - name: remoting
      port: 25520
      targetPort: 25520
      protocol: TCP
    - name: management
      port: 8558
      targetPort: 8558
      protocol: TCP
