---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akka-sharding-sa
  namespace: akka-sharding

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akka-sharding-role
  namespace: akka-sharding
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: akka-sharding-rolebinding
  namespace: akka-sharding
subjects:
  - kind: ServiceAccount
    name: akka-sharding-sa
    namespace: akka-sharding
roleRef:
  kind: Role
  name: akka-sharding-role
  apiGroup: rbac.authorization.k8s.io
